### ISSUE TITLE
allow multiple domain to be listed

### ISSUE THREAD

**Issue by Folleach** [Folleach/mineginx#2]
```yaml
# config/mineginx.yaml
servers:
- listen: "0.0.0.0:7878"
  server_name:
  - localhost
  - another.localhost
  proxy_pass: "127.0.0.1:25565"
```
