### ISSUE TITLE
time-out when handshake is inactive

### ISSUE THREAD

**Issue by Folleach** [Folleach/mineginx#5]
For example, when client open the connection and do not send any bytes

**Comment by Folleach** [comment]
Now timeout can be specified in `config/mineginx.yaml` with `handshake_timeout_ms`
```yaml
handshake_timeout_ms: 30000 # 30 seconds
servers:
- listen: "0.0.0.0:7878"
  server_names:
  - "localhost"
  - "another.localhost"
  proxy_pass: "127.0.0.1:25565"
```

If someone connect and do not send any bytes, their connection will be closed after specified interval.  
You can try it with netcat or similar utilities
```bash
nc localhost 7878
```
