### ISSUE TITLE
Forge client cant connect to server

### ISSUE THREAD

**Issue by ktnk-dev** [Folleach/mineginx#7]
# Description
Forge players cant connect to server (maybe same with fabric?)

# Steps to reproduce
1. Run game with Forge Mod Loader (tested on 1.19.4)
2. Try to connect to server

# Config
```yaml
- listen: "0.0.0.0:25565"
  server_names: 
  - "mc.example.com"
  proxy_pass: "10.0.0.1:7777"
```
Error: `there is no upstream for domain "mc.example.com\0FML3\0"`

# Temporary solution
- Put `\0FML3\0` in `server_names`
```yaml
- listen: "0.0.0.0:25565"
  server_names: 
  - "mc.example.com\0FML3\0"
  proxy_pass: "10.0.0.1:7777"
```
