### ISSUE TITLE
IP ban list?

### ISSUE THREAD

**Issue by ktnk-dev** [Folleach/mineginx#8]
# Feature request
Add IP ban list to mineginx

# Problem
By default all connections via mineginx are routing in "local" network, so you cant ban player by ip.
Player's ip is `9.9.9.9` for example, but minecraft server think that it is `1.1.1.1`.
Another player have `9.9.8.8` ip, but server still see `1.1.1.1`.

# My example
```yaml
- listen: "0.0.0.0:25565"
  server_names: 
  - "mc.example.com"
  proxy_pass: "10.0.0.1:7777"
  banned_ips: 
  - "9.9.9.9"
  - "9.9.8.x"
```
```css
client > [check for server_names] > [check for banned_ips] > server
```
